# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Style Check
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm run check

  build:
    runs-on: ubuntu-latest
    needs: style-check

    strategy:
      matrix:
        node-version: [10.x, 13.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run compile --if-present
