name: Python package

on: [push, pull_request]

jobs:
  super-lint:
    name: Run Github Super Linter on Full code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_YAML: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_PYTHON: false
          VALIDATE_DOCKER: true
          VALIDATE_ENV: true

  lint:
    name: Style check
    runs-on: ubuntu-latest
    steps:
      - uses: jpetrucciani/black-check@master
